version: "3.7"

services:
  servidor:
    image: fjortegan/dwes:laravel
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:80"
    # development
    volumes:
      - ./laravel:/var/www/html/
    # Sólo en máquinas Linux, comentar estas dos líneas en otros sistemas de lusers
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    command: >
      /bin/bash -c "apt-get update && \
      apt-get install -y vim && \
      apt-get install -y php-dev && \
      docker-php-ext-install pdo_mysql && \
      php-fpm -F"


  db:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: quizz-app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
